// `useHello` is generated by orval from the backend module's OpenAPI schema
// (run `pnpm run build:modules`, which regenerates `src/api/example.ts`).
import { useHello } from "../api/example";
import Alignments from "../pages/alignments";

export default function Hello() {
  const { data, isPending, isError } = useHello();

  return (
    <div>
      <h1>Example module</h1>
      <Alignments />
    </div>
  );
}
